### ISSUE TITLE
Pull request fire-drill

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/lef#2]
The below looks like a pullrequest with a straightforward bugfix.

Any reason why it hasn't been commented on or merged?

https://github.com/The-OpenROAD-Project/lef/pull/1

**Comment by mgwoo** [comment]
Sorry for the late reply... I didn't notice that you raised a PR in this repo. (I enabled watching mode in the lef/def repo today.)
Your update has been updated in the recent PR.
Thank you very much.

**Comment by oharboe** [comment]
thanks!

fre. 15. nov. 2019, 07:39 skrev Mingyu Woo <notifications@github.com>:
